AWSTemplateFormatVersion: 2010-09-09
Description: Configure the Cross-Account IAM Audit Roles for Audit Account

Parameters:
  ManagedResourcePrefix:
    Type: 'String'
    Description: "Managed Resource Prefix"
  AuditAccountId:
    Type: 'String'
    Description: 'Audit account Id'
  LoggingAccountId:
    Type: 'String'
    Description: 'Logging account Id'

Resources:
  # AWSConfig Aggregator for Guardrail compliance
  GuardrailsComplianceAggregator:
    Type: AWS::Config::ConfigurationAggregator
    Properties:
      AccountAggregationSources:
        - AccountIds:
          - !Ref AuditAccountId
          - !Ref LoggingAccountId
          AllAwsRegions: true
      ConfigurationAggregatorName: !Sub ${ManagedResourcePrefix}-GuardrailsComplianceAggregator